### PR TITLE
kiss-initpkg: add to contrib

### PR DESCRIPTION
**Pull request by cemkeylan**
I had this in my shellrc, thought I would share it. Someone could find it useful. Any ideas?

### CODE REVIEW

**Comment by cemkeylan** [comment]
That's weird shellcheck did not give an error before I committed, I always do this stuff on my scripts.

**Comment by dylanaraps** [comment]
I personally use:

```sh
#!/bin/sh

die() {
    printf 'error: %s.\n' "$*" >&2
    exit 1
}

log() {
    printf '=> %s.\n' "$*"
}

main() {
    [ "$1" ] || {
        cat <<-EOF
			Create boilerplate KISS packages.

			arg 1 - Package name (required).
			arg 2 - Package version (optional).
			arg 3 - Package source (optional).

		EOF

        exit
    }

    [ -d "$1" ] &&
        die Package "$1" already exists

    mkdir -p "$1" ||
        die Couldn\'t create directory in "$PWD"

    cd "$1" ||
        die Couldn\'t enter directory "$1/"

    log Populating build file; {
        printf '#!/bin/sh -e\n' > build
        chmod +x build
    }

    log Populating version file with "'${2%% *} 1'"; {
         printf '%s\n' "${2%% *} 1" > version
    }

    log Populating sources file with "'$3'"; {
        printf '%s\n' "$3" > sources
    }
}

main "$@"
```

I've been meaning to clean this up and push it!

**Comment by cemkeylan** [comment]
Actually having a `$2` and `$3` for version and sources make much more sense. Adding multiple packages in a single command is not that common either. We could simplify yours a little bit and add that instead!

**Comment by cemkeylan** [comment]
I am gonna go ahead and disable shellcheck errors, I know `A && B || C is not if-then-else`

**Comment by dylanaraps** [comment]
Added as `kiss-new` here: https://github.com/kisslinux/kiss/commit/17ee3eaed4f41565d2fd5cafb2d8063eddf39e08

**Pull request closed without merging**
